name: jobhub
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_chat_bubble: ^2.0.2
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  flutter_vector_icons: ^2.0.0
  flutter_zoom_drawer: ^3.0.4+1
  get: ^4.6.5
  google_fonts: ^4.0.3
  http: ^0.13.5
  image_cropper: ^3.0.3
  image_picker: ^0.8.7+4
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
